import { Timestamp } from '@angular/fire/firestore';

export interface Job {
  id: string;
  jobType: 'Standard' | 'Split Journey';
  customerReference: string;
  shippingReference: string;
  priority: boolean;
  vehicleType: 'Car' | 'Van' | 'Truck' | 'Motorcycle';
  vehicleMake: string;
  vehicleModel: string;
  vehicleRegistration: string;
  vehicleYear: number;
  vehicleLocation: string;
  collectionBuilding: string;
  collectionStreet: string;
  collectionCity: string;
  collectionPostcode: string;
  collectionCountry: string;
  collectionContactName: string;
  collectionContactPhone: string;
  collectionContactEmail: string;
  collectionInstructions: string;
  deliveryBuilding: string;
  deliveryStreet: string;
  deliveryCity: string;
  deliveryPostcode: string;
  deliveryCountry: string;
  deliveryContactName: string;
  deliveryContactPhone: string;
  deliveryContactEmail: string;
  deliveryInstructions: string;
  secondaryPoints?: {
    building: string;
    street: string;
    city: string;
    postcode: string;
    country: string;
    contactName: string;
    contactPhone: string;
    contactEmail: string;
    instructions: string;
  }[];
  team: string;
  currentDriver?: string;
  status: 'Unallocated' | 'Allocated' | 'Collected' | 'Delivered' | 'Cancelled';
  collectionDate: Timestamp;
  deliveryDate: Timestamp;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}
